using System;

namespace Penumbra.GameData.Enums;

public enum WeaponCategory : byte
{
    Unknown = 0,
    Pugilist,
    Gladiator,
    Marauder,
    Archer,
    Lancer,
    Thaumaturge1,
    Thaumaturge2,
    Conjurer1,
    Conjurer2,
    Arcanist,
    Shield,
    CarpenterMain,
    CarpenterOff,
    BlacksmithMain,
    BlacksmithOff,
    ArmorerMain,
    ArmorerOff,
    GoldsmithMain,
    GoldsmithOff,
    LeatherworkerMain,
    LeatherworkerOff,
    WeaverMain,
    WeaverOff,
    AlchemistMain,
    AlchemistOff,
    CulinarianMain,
    CulinarianOff,
    MinerMain,
    MinerOff,
    BotanistMain,
    BotanistOff,
    FisherMain,
    Rogue       = 84,
    DarkKnight  = 87,
    Machinist   = 88,
    Astrologian = 89,
    Samurai     = 96,
    RedMage     = 97,
    Scholar     = 98,
    FisherOff   = 99,
    BlueMage    = 105,
    Gunbreaker  = 106,
    Dancer      = 107,
    Reaper      = 108,
    Sage        = 109,
}