using System;
using System.Runtime.InteropServices;

namespace Penumbra.Import.Dds;

[StructLayout( LayoutKind.Sequential )]
public struct DXT10Header
{
    public DXGIFormat           Format;
    public D3DResourceDimension ResourceDimension;
    public D3DResourceMiscFlags MiscFlags;
    public uint                 ArraySize;
    public D3DAlphaMode         AlphaMode;

    public ParseType ToParseType()
    {
        return Format switch
        {
            DXGIFormat.BC1Typeless  => ParseType.DXT1,
            DXGIFormat.BC1UNorm     => ParseType.DXT1,
            DXGIFormat.BC1UNormSRGB => ParseType.DXT1,

            DXGIFormat.BC2Typeless  => ParseType.DXT3,
            DXGIFormat.BC2UNorm     => ParseType.DXT3,
            DXGIFormat.BC2UNormSRGB => ParseType.DXT3,

            DXGIFormat.BC3Typeless  => ParseType.DXT5,
            DXGIFormat.BC3UNorm     => ParseType.DXT5,
            DXGIFormat.BC3UNormSRGB => ParseType.DXT5,

            DXGIFormat.BC4Typeless => ParseType.BC4,
            DXGIFormat.BC4SNorm    => ParseType.BC4,
            DXGIFormat.BC4UNorm    => ParseType.BC4,

            DXGIFormat.BC5Typeless => ParseType.BC5,
            DXGIFormat.BC5SNorm    => ParseType.BC5,
            DXGIFormat.BC5UNorm    => ParseType.BC5,

            DXGIFormat.R8G8B8A8Typeless  => ParseType.R8G8B8A8,
            DXGIFormat.R8G8B8A8UNorm     => ParseType.R8G8B8A8,
            DXGIFormat.R8G8B8A8UNormSRGB => ParseType.R8G8B8A8,
            DXGIFormat.R8G8B8A8UInt      => ParseType.R8G8B8A8,
            DXGIFormat.R8G8B8A8SNorm     => ParseType.R8G8B8A8,
            DXGIFormat.R8G8B8A8SInt      => ParseType.R8G8B8A8,

            DXGIFormat.B8G8R8A8Typeless  => ParseType.B8G8R8A8,
            DXGIFormat.B8G8R8A8UNorm     => ParseType.B8G8R8A8,
            DXGIFormat.B8G8R8A8UNormSRGB => ParseType.B8G8R8A8,
            DXGIFormat.B8G8R8X8Typeless  => ParseType.B8G8R8A8,
            DXGIFormat.B8G8R8X8UNorm     => ParseType.B8G8R8A8,
            DXGIFormat.B8G8R8X8UNormSRGB => ParseType.B8G8R8A8,

            DXGIFormat.B4G4R4A4UNorm => ParseType.B4G4R4A4,
            DXGIFormat.B5G5R5A1UNorm => ParseType.B5G5R5A1,
            DXGIFormat.B5G6R5UNorm   => ParseType.B5G6R5,

            DXGIFormat.BC6HSF16     => ParseType.Unsupported,
            DXGIFormat.BC6HTypeless => ParseType.Unsupported,
            DXGIFormat.BC6HUF16     => ParseType.Unsupported,

            DXGIFormat.BC7Typeless  => ParseType.Unsupported,
            DXGIFormat.BC7UNorm     => ParseType.Unsupported,
            DXGIFormat.BC7UNormSRGB => ParseType.Unsupported,

            DXGIFormat.Unknown                            => ParseType.Unsupported,
            DXGIFormat.R32G32B32A32Typeless               => ParseType.Unsupported,
            DXGIFormat.R32G32B32A32Float                  => ParseType.Unsupported,
            DXGIFormat.R32G32B32A32UInt                   => ParseType.Unsupported,
            DXGIFormat.R32G32B32A32SInt                   => ParseType.Unsupported,
            DXGIFormat.R32G32B32Typeless                  => ParseType.Unsupported,
            DXGIFormat.R32G32B32Float                     => ParseType.Unsupported,
            DXGIFormat.R32G32B32UInt                      => ParseType.Unsupported,
            DXGIFormat.R32G32B32SInt                      => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16Typeless               => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16Float                  => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16UNorm                  => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16UInt                   => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16SNorm                  => ParseType.Unsupported,
            DXGIFormat.R16G16B16A16SInt                   => ParseType.Unsupported,
            DXGIFormat.R32G32Typeless                     => ParseType.Unsupported,
            DXGIFormat.R32G32Float                        => ParseType.Unsupported,
            DXGIFormat.R32G32UInt                         => ParseType.Unsupported,
            DXGIFormat.R32G32SInt                         => ParseType.Unsupported,
            DXGIFormat.R32G8X24Typeless                   => ParseType.Unsupported,
            DXGIFormat.D32FloatS8X24UInt                  => ParseType.Unsupported,
            DXGIFormat.R32FloatX8X24Typeless              => ParseType.Unsupported,
            DXGIFormat.X32TypelessG8X24UInt               => ParseType.Unsupported,
            DXGIFormat.R10G10B10A2Typeless                => ParseType.Unsupported,
            DXGIFormat.R10G10B10A2UNorm                   => ParseType.Unsupported,
            DXGIFormat.R10G10B10A2UInt                    => ParseType.Unsupported,
            DXGIFormat.R11G11B10Float                     => ParseType.Unsupported,
            DXGIFormat.R16G16Typeless                     => ParseType.Unsupported,
            DXGIFormat.R16G16Float                        => ParseType.Unsupported,
            DXGIFormat.R16G16UNorm                        => ParseType.Unsupported,
            DXGIFormat.R16G16UInt                         => ParseType.Unsupported,
            DXGIFormat.R16G16SNorm                        => ParseType.Unsupported,
            DXGIFormat.R16G16SInt                         => ParseType.Unsupported,
            DXGIFormat.R32Typeless                        => ParseType.Unsupported,
            DXGIFormat.D32Float                           => ParseType.Unsupported,
            DXGIFormat.R32Float                           => ParseType.Unsupported,
            DXGIFormat.R32UInt                            => ParseType.Unsupported,
            DXGIFormat.R32SInt                            => ParseType.Unsupported,
            DXGIFormat.R24G8Typeless                      => ParseType.Unsupported,
            DXGIFormat.D24UNormS8UInt                     => ParseType.Unsupported,
            DXGIFormat.R24UNormX8Typeless                 => ParseType.Unsupported,
            DXGIFormat.X24TypelessG8UInt                  => ParseType.Unsupported,
            DXGIFormat.R8G8Typeless                       => ParseType.Unsupported,
            DXGIFormat.R8G8UNorm                          => ParseType.Unsupported,
            DXGIFormat.R8G8UInt                           => ParseType.Unsupported,
            DXGIFormat.R8G8SNorm                          => ParseType.Unsupported,
            DXGIFormat.R8G8SInt                           => ParseType.Unsupported,
            DXGIFormat.R16Typeless                        => ParseType.Unsupported,
            DXGIFormat.R16Float                           => ParseType.Unsupported,
            DXGIFormat.D16UNorm                           => ParseType.Unsupported,
            DXGIFormat.R16UNorm                           => ParseType.Unsupported,
            DXGIFormat.R16UInt                            => ParseType.Unsupported,
            DXGIFormat.R16SNorm                           => ParseType.Unsupported,
            DXGIFormat.R16SInt                            => ParseType.Unsupported,
            DXGIFormat.R8Typeless                         => ParseType.Unsupported,
            DXGIFormat.R8UNorm                            => ParseType.Unsupported,
            DXGIFormat.R8UInt                             => ParseType.Unsupported,
            DXGIFormat.R8SNorm                            => ParseType.Unsupported,
            DXGIFormat.R8SInt                             => ParseType.Unsupported,
            DXGIFormat.A8UNorm                            => ParseType.Unsupported,
            DXGIFormat.R1UNorm                            => ParseType.Unsupported,
            DXGIFormat.R9G9B9E5SharedEXP                  => ParseType.Unsupported,
            DXGIFormat.R8G8B8G8UNorm                      => ParseType.Unsupported,
            DXGIFormat.G8R8G8B8UNorm                      => ParseType.Unsupported,
            DXGIFormat.R10G10B10XRBiasA2UNorm             => ParseType.Unsupported,
            DXGIFormat.AYUV                               => ParseType.Unsupported,
            DXGIFormat.Y410                               => ParseType.Unsupported,
            DXGIFormat.Y416                               => ParseType.Unsupported,
            DXGIFormat.NV12                               => ParseType.Unsupported,
            DXGIFormat.P010                               => ParseType.Unsupported,
            DXGIFormat.P016                               => ParseType.Unsupported,
            DXGIFormat.F420Opaque                         => ParseType.Unsupported,
            DXGIFormat.YUY2                               => ParseType.Unsupported,
            DXGIFormat.Y210                               => ParseType.Unsupported,
            DXGIFormat.Y216                               => ParseType.Unsupported,
            DXGIFormat.NV11                               => ParseType.Unsupported,
            DXGIFormat.AI44                               => ParseType.Unsupported,
            DXGIFormat.IA44                               => ParseType.Unsupported,
            DXGIFormat.P8                                 => ParseType.Unsupported,
            DXGIFormat.A8P8                               => ParseType.Unsupported,
            DXGIFormat.P208                               => ParseType.Unsupported,
            DXGIFormat.V208                               => ParseType.Unsupported,
            DXGIFormat.V408                               => ParseType.Unsupported,
            DXGIFormat.SamplerFeedbackMinMipOpaque        => ParseType.Unsupported,
            DXGIFormat.SamplerFeedbackMipRegionUsedOpaque => ParseType.Unsupported,
            DXGIFormat.ForceUInt                          => ParseType.Unsupported,
            _                                             => ParseType.Unsupported,
        };
    }

    public enum DXGIFormat : uint
    {
        Unknown                = 0,
        R32G32B32A32Typeless   = 1,
        R32G32B32A32Float      = 2,
        R32G32B32A32UInt       = 3,
        R32G32B32A32SInt       = 4,
        R32G32B32Typeless      = 5,
        R32G32B32Float         = 6,
        R32G32B32UInt          = 7,
        R32G32B32SInt          = 8,
        R16G16B16A16Typeless   = 9,
        R16G16B16A16Float      = 10,
        R16G16B16A16UNorm      = 11,
        R16G16B16A16UInt       = 12,
        R16G16B16A16SNorm      = 13,
        R16G16B16A16SInt       = 14,
        R32G32Typeless         = 15,
        R32G32Float            = 16,
        R32G32UInt             = 17,
        R32G32SInt             = 18,
        R32G8X24Typeless       = 19,
        D32FloatS8X24UInt      = 20,
        R32FloatX8X24Typeless  = 21,
        X32TypelessG8X24UInt   = 22,
        R10G10B10A2Typeless    = 23,
        R10G10B10A2UNorm       = 24,
        R10G10B10A2UInt        = 25,
        R11G11B10Float         = 26,
        R8G8B8A8Typeless       = 27,
        R8G8B8A8UNorm          = 28,
        R8G8B8A8UNormSRGB      = 29,
        R8G8B8A8UInt           = 30,
        R8G8B8A8SNorm          = 31,
        R8G8B8A8SInt           = 32,
        R16G16Typeless         = 33,
        R16G16Float            = 34,
        R16G16UNorm            = 35,
        R16G16UInt             = 36,
        R16G16SNorm            = 37,
        R16G16SInt             = 38,
        R32Typeless            = 39,
        D32Float               = 40,
        R32Float               = 41,
        R32UInt                = 42,
        R32SInt                = 43,
        R24G8Typeless          = 44,
        D24UNormS8UInt         = 45,
        R24UNormX8Typeless     = 46,
        X24TypelessG8UInt      = 47,
        R8G8Typeless           = 48,
        R8G8UNorm              = 49,
        R8G8UInt               = 50,
        R8G8SNorm              = 51,
        R8G8SInt               = 52,
        R16Typeless            = 53,
        R16Float               = 54,
        D16UNorm               = 55,
        R16UNorm               = 56,
        R16UInt                = 57,
        R16SNorm               = 58,
        R16SInt                = 59,
        R8Typeless             = 60,
        R8UNorm                = 61,
        R8UInt                 = 62,
        R8SNorm                = 63,
        R8SInt                 = 64,
        A8UNorm                = 65,
        R1UNorm                = 66,
        R9G9B9E5SharedEXP      = 67,
        R8G8B8G8UNorm          = 68,
        G8R8G8B8UNorm          = 69,
        BC1Typeless            = 70,
        BC1UNorm               = 71,
        BC1UNormSRGB           = 72,
        BC2Typeless            = 73,
        BC2UNorm               = 74,
        BC2UNormSRGB           = 75,
        BC3Typeless            = 76,
        BC3UNorm               = 77,
        BC3UNormSRGB           = 78,
        BC4Typeless            = 79,
        BC4UNorm               = 80,
        BC4SNorm               = 81,
        BC5Typeless            = 82,
        BC5UNorm               = 83,
        BC5SNorm               = 84,
        B5G6R5UNorm            = 85,
        B5G5R5A1UNorm          = 86,
        B8G8R8A8UNorm          = 87,
        B8G8R8X8UNorm          = 88,
        R10G10B10XRBiasA2UNorm = 89,
        B8G8R8A8Typeless       = 90,
        B8G8R8A8UNormSRGB      = 91,
        B8G8R8X8Typeless       = 92,
        B8G8R8X8UNormSRGB      = 93,
        BC6HTypeless           = 94,
        BC6HUF16               = 95,
        BC6HSF16               = 96,
        BC7Typeless            = 97,
        BC7UNorm               = 98,
        BC7UNormSRGB           = 99,
        AYUV                   = 100,
        Y410                   = 101,
        Y416                   = 102,
        NV12                   = 103,
        P010                   = 104,
        P016                   = 105,
        F420Opaque             = 106,
        YUY2                   = 107,
        Y210                   = 108,
        Y216                   = 109,
        NV11                   = 110,
        AI44                   = 111,
        IA44                   = 112,
        P8                     = 113,
        A8P8                   = 114,
        B4G4R4A4UNorm          = 115,
        P208                   = 130,
        V208                   = 131,
        V408                   = 132,
        SamplerFeedbackMinMipOpaque,
        SamplerFeedbackMipRegionUsedOpaque,
        ForceUInt = 0xffffffff,
    }

    public enum D3DResourceDimension : int
    {
        Unknown   = 0,
        Buffer    = 1,
        Texture1D = 2,
        Texture2D = 3,
        Texture3D = 4,
    }

    [Flags]
    public enum D3DResourceMiscFlags : uint
    {
        GenerateMips                 = 0x000001,
        Shared                       = 0x000002,
        TextureCube                  = 0x000004,
        DrawIndirectArgs             = 0x000010,
        BufferAllowRawViews          = 0x000020,
        BufferStructured             = 0x000040,
        ResourceClamp                = 0x000080,
        SharedKeyedMutex             = 0x000100,
        GDICompatible                = 0x000200,
        SharedNTHandle               = 0x000800,
        RestrictedContent            = 0x001000,
        RestrictSharedResource       = 0x002000,
        RestrictSharedResourceDriver = 0x004000,
        Guarded                      = 0x008000,
        TilePool                     = 0x020000,
        Tiled                        = 0x040000,
        HWProtected                  = 0x080000,
        SharedDisplayable,
        SharedExclusiveWriter,
    };

    public enum D3DAlphaMode : int
    {
        Unknown       = 0,
        Straight      = 1,
        Premultiplied = 2,
        Opaque        = 3,
        Custom        = 4,
    };
}