name: .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: ./.github/workflows/prepare-environment.yml
      - name: Build
        run: |
          dotnet build --no-restore --configuration Release --nologo
      - name: Archive
        run: Compress-Archive -Path Penumbra/bin/Release/* -DestinationPath Penumbra.zip
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: |
            ./Penumbra/bin/Release/*
