name: .NET Build

on:
  push:
    branches: '*'
    tags-ignore: '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Prepare Environment
        uses: ./.github/actions/prepare-environment
      - name: Build and Upload Artifact
        uses: ./.github/actions/build-with-artifact
        with:
          project: Penumbra
